/**
 * PaperNote Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request containing multiple user IDs to resolve to their corresponding usernames
 */
export interface BatchUserIdResolutionRequestDto { 
    userIds?: Array<string> | null;
}

