/**
 * PaperNote Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request containing multiple usernames to resolve to their corresponding user IDs
 */
export interface BatchUserResolutionRequestDto { 
    usernames?: Array<string> | null;
}

