/**
 * PaperNote Auth API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User profile information including account details and activity timestamps
 */
export interface UserDto { 
    id?: string;
    username?: string | null;
    createdAt?: string;
    lastLoginAt?: string | null;
}

