// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Papernote.Notes.Infrastructure.Persistence;

#nullable disable

namespace Papernote.Notes.Infrastructure.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20250911152751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("papernote")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notes_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_notes_is_deleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_notes_updated_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notes_user_id");

                    b.ToTable("notes", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_at");

                    b.Property<Guid>("SharedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_by_user_id");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("shared_with_user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_note_shares_is_revoked");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_shares_note_id");

                    b.HasIndex("SharedAt")
                        .HasDatabaseName("ix_note_shares_shared_at");

                    b.HasIndex("SharedByUserId")
                        .HasDatabaseName("ix_note_shares_shared_by_user_id");

                    b.HasIndex("SharedWithUserId")
                        .HasDatabaseName("ix_note_shares_shared_with_user_id");

                    b.HasIndex("NoteId", "SharedWithUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_note_shares_note_user_active")
                        .HasFilter("is_revoked = false");

                    b.ToTable("note_shares", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("AddedAt")
                        .HasDatabaseName("ix_note_tags_added_at");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_tags_note_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_note_tags_tag_id");

                    b.ToTable("note_tags", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tags_created_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name_unique");

                    b.ToTable("tags", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteShare", b =>
                {
                    b.HasOne("Papernote.Notes.Core.Domain.Entities.Note", "Note")
                        .WithMany("NoteShares")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("Papernote.Notes.Core.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papernote.Notes.Core.Domain.Entities.TagEntity", "Tag")
                        .WithMany("NoteTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Navigation("NoteShares");

                    b.Navigation("NoteTags");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.TagEntity", b =>
                {
                    b.Navigation("NoteTags");
                });
#pragma warning restore 612, 618
        }
    }
}
