// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Papernote.Notes.Infrastructure.Persistence;

#nullable disable

namespace Papernote.Notes.Infrastructure.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20250912184316_AddUserOwnershipAndSharing")]
    partial class AddUserOwnershipAndSharing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("papernote")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("\r\n                setweight(to_tsvector('italian', coalesce(title,   '')), 'A') ||\r\n                setweight(to_tsvector('italian', coalesce(content, '')), 'B')\r\n            ", true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notes_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_notes_is_deleted");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_notes_owner_user_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_notes_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_notes_updated_at");

                    b.ToTable("notes", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteShare", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid>("ReaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reader_user_id");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shared_at");

                    b.HasKey("NoteId", "ReaderUserId");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_shares_note_id");

                    b.HasIndex("ReaderUserId")
                        .HasDatabaseName("ix_note_shares_reader_user_id");

                    b.HasIndex("SharedAt")
                        .HasDatabaseName("ix_note_shares_shared_at");

                    b.HasIndex("NoteId", "ReaderUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_note_shares_note_reader");

                    b.ToTable("note_shares", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("NoteId", "TagName");

                    b.HasIndex("AddedAt")
                        .HasDatabaseName("ix_note_tags_added_at");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_tags_note_id");

                    b.HasIndex("TagName")
                        .HasDatabaseName("ix_note_tags_tag_name");

                    b.ToTable("note_tags", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteShare", b =>
                {
                    b.HasOne("Papernote.Notes.Core.Domain.Entities.Note", "Note")
                        .WithMany("NoteShares")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("Papernote.Notes.Core.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Navigation("NoteShares");

                    b.Navigation("NoteTags");
                });
#pragma warning restore 612, 618
        }
    }
}
