// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Papernote.Notes.Infrastructure.Persistence;

#nullable disable

namespace Papernote.Notes.Infrastructure.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20250911180758_SimplifiedNotesModel")]
    partial class SimplifiedNotesModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("papernote")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_notes_created_at");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_notes_is_deleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_notes_updated_at");

                    b.ToTable("notes", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tag_name");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("NoteId", "TagName");

                    b.HasIndex("AddedAt")
                        .HasDatabaseName("ix_note_tags_added_at");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_note_tags_note_id");

                    b.HasIndex("TagName")
                        .HasDatabaseName("ix_note_tags_tag_name");

                    b.ToTable("note_tags", "papernote");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.NoteTag", b =>
                {
                    b.HasOne("Papernote.Notes.Core.Domain.Entities.Note", "Note")
                        .WithMany("NoteTags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("Papernote.Notes.Core.Domain.Entities.Note", b =>
                {
                    b.Navigation("NoteTags");
                });
#pragma warning restore 612, 618
        }
    }
}
